%This scrpt merge all localizations in specified folder with extension .csv
%If it is generated by STORM experiment, the files will be named:
%BLABLA.csv, BLABLA_X2.csv, BLABLA_X3.csv etc
clear all
clc
disp('choose folder with localizations files')
folder = uigetdir

list_of_files = dir(folder);

%choose only csv files
ii = 1;
for i=3:size(list_of_files,1)
    
    if list_of_files(i).name(end-3:end) == '.csv'
        Excel_files(ii).name = list_of_files(i).name;
        ii=ii+1;
    end
end

%open and save all tables

for i=1:size(Excel_files,2)
    disp(['I am opening the file: ' Excel_files(i).name])
    
    locs = ReadLocFile_thunder([folder '\' Excel_files(i).name]);
    %update frame numbers
    if i==1
       Locs = locs;
    else
       locs.frame = locs.frame+Locs.frame(end);
       Locs = [Locs; locs];
    end
    
end


NewName = [folder '\' Excel_files(1).name(1:end-4) '_all_locs.csv'];
disp(['I am writing the file: ' NewName])

writetable(Locs, NewName);